### ISSUE TITLE
remoteId is the only criterion in deleteByIds

### ISSUE THREAD

**Issue by shunf4** [readrops/Readrops#100]
https://github.com/readrops/Readrops/blob/52fda0f8d8be57b4515b3f78b34ed9bbcc047886/db/src/main/java/com/readrops/db/dao/FeedDao.java#L130

https://github.com/readrops/Readrops/blob/52fda0f8d8be57b4515b3f78b34ed9bbcc047886/db/src/main/java/com/readrops/db/dao/FeedDao.java#L84-L85

Isn't is possible that two feeds in two different FreshRSS instances share the same `remoteId`? It's dangerous we use `remoteId` as the only condition to do deletion.

**Comment by Shinokuni** [comment]
Thank you for pointing this out, indeed this could delete ids from multiple accounts.
