### ISSUE TITLE
Feature suggestion: hide feeds/folders with 0 unread items

### ISSUE THREAD

**Issue by 360fun** [readrops/Readrops#101]
Hi, finally I'm able to use your client with FreshRSS! 😄 

The first sensation was "why so many feeds/folders?" and then I realised that normally others clients allow me to show only unread items: would be great if Readrops could do the same! :)

**Comment by Shinokuni** [comment]
This feature was added in 1bfed8306d00cfcd17fac5892d0462841aeada57, as a parameter, disabled by default.

**Comment by 360fun** [comment]
great, I'll wait the update :)
