### ISSUE TITLE
Export OPML

### ISSUE THREAD

**Issue by tomgue** [readrops/Readrops#107]
Bonjour,
L'exportation des feed ne fonctionne pas chez moi suis-je le seul ?
![Readrops.gif](https://user-images.githubusercontent.com/4108018/119795681-fd7d6900-bed8-11eb-9c77-7facaebb17b3.gif)

**Comment by Shinokuni** [comment]
Le message d'erreur indique qu'il y a au moins un flux en base qui ne possède pas d'url. Ce qui est troublant, c'est comment cette situation peut se produire.

Quel type de compte avez-vous ?

**Comment by tomgue** [comment]
Un compte local simple 🤔

**Comment by Shinokuni** [comment]
Avez-vous importé un fichier OPML en créant le compte ? Avec un compte local, il me semble que c'est la seule manière de se retrouver avec un flux sans url.

Si c'est le cas, vous pouvez corriger la situation en rajoutant l'url manquante au flux concerné dans l'écran de gestion des flux.

**Comment by tomgue** [comment]
Il me semble pas avoir fait d'importation, mais je vais vérifier chaque flux... Ça va être long 😆

**Comment by Shinokuni** [comment]
Avez-vous réussi à vérifier vos flux ?

**Comment by tomgue** [comment]
Effectivement j'ai vérifié chaque flux et aucune URL manquantes, mais maintenant quand je sélectionne l'export il ne se passe rien...

**Comment by Shinokuni** [comment]
Je ferme ce ticket, vous pouvez le rouvrir si vous avez toujours des problèmes.
