### ISSUE TITLE
Suddenly can't sync any-more

### ISSUE THREAD

**Issue by keunes** [readrops/Readrops#108]
Hello

I've been using Readrops for a long time, but suddenly (since a week or so) I can't seem to sync any-more.

When doing a pull-to-refresh, no new articles appear and an empty snackbar is shown:

![Screenshot_20210715-090825.png](https://user-images.githubusercontent.com/11229646/125745200-ba5763ba-42f2-4b51-887a-56f1634a8a9a.png)

Could this perhaps be related to [recent changes in Nextcloud News](https://github.com/nextcloud/news/blob/master/CHANGELOG.md#1600---2021-06-16)?

I'm on Readrops 1.2.1

**Comment by Shinokuni** [comment]
Did you check your feeds on Nextcloud? I have the same problem with my instance (v16.0.0) but I haven´t taken time to investigate.

**Comment by keunes** [comment]
@Shinokuni Sorry - had a small holiday in between. I just checked, and all feeds seem up to date on my server.
When I refresh, I see the following log entry appearing on my log web interface:

```
[index] Error: Exception: Argument 3 passed to OCA\News\Service\ItemServiceV2::findAllAfter() must be of the type int, float given, called in /var/www/nextcloud/apps/news/lib/Controller/ItemApiController.php on line 147 at <<closure>>

0. /var/www/nextcloud/lib/private/AppFramework/App.php line 152
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\News\Controller\ItemApiController {}, "updated")
1. /var/www/nextcloud/lib/private/Route/Router.php line 309
   OC\AppFramework\App::main("OCA\\News\\Cont ... r", "updated", OC\AppFramework\ ... {}, {_route: "news.item_api.updated"})
2. /var/www/nextcloud/lib/base.php line 1008
   OC\Route\Router->match("/apps/news/api/v1-2/items/updated")
3. /var/www/nextcloud/index.php line 37
   OC::handleRequest()

GET /index.php/apps/news/api/v1-2/items/updated?lastModified=1625656345&type=3
from 192.168.xxx.xx by keunes at 2021-07-25T14:46:29+00:00
```

**Comment by keunes** [comment]
Same bug reported in https://github.com/bubelov/news/issues/72

**Comment by Shinokuni** [comment]
You should report the error to the Nextcloud News devs, it clearly seems a backend issue. I would like to know too how to fix this issue as it makes News completely unusable.

**Comment by keunes** [comment]
Ok, thanks. I have, see automatic link above :)

**Comment by Shinokuni** [comment]
So the problem comes from the News app. Tell me if you got the synchronization working back with either downgrading the News app version or upgrade to a 64bits OS.

**Comment by keunes** [comment]
I upgraded to a 64 bits OS and it now works indeed. Closing this issue.
