### ISSUE TITLE
[Feature] Add ability to mark article as unread from the article itself

### ISSUE THREAD

**Issue by GLLM** [readrops/Readrops#112]
Hi,

I have a request :
Note : I only show unread articles. Always.

I often browse thru my feeds and see articles which looks interesting. When I do so, I open them to read them but realize I wont have enough time to read them entirely. Or even do not even start reading and want to read them later.
But I cannot mark it as unread from within the article.
So I exit the article and voilà ... I cannot see it anymore !

I need to change the display again to display unread & read articles, find it (sometimes it's lost in tons of articles) and mark it as unread. Then again, change the display to 'unread article only'.

If we could have a shortcut to mark an item as unread from the opened articles, it would be grateful !

Many thanks
GLLM

**Comment by fn-ix** [comment]
Or alternatively, a toggle in the settings that disables marking articles as read when they're opened, given the existing unobtrusive mark-as-read swipe in the feed view.

**Comment by Shinokuni** [comment]
Added in 2.0. The first beta is [available](https://github.com/readrops/Readrops/releases/tag/v2.0-beta01) to test if you would like so.
