### ISSUE TITLE
Cannot enable storage permission

### ISSUE THREAD

**Issue by shockinghuman** [readrops/Readrops#118]
When trying to download an image a popup at the buttom of the screen says to allow storage access and provides a button to the app info in settings. When I open permissions I don't see any switches and when I go to storage permissions in settings the app is not on the list of apps that I can enable the permission for. I am using Android 11, is storage access for this version of android supported?

**Comment by Shinokuni** [comment]
Should be fixed in 2.0 as no storage permission is required now.
