### ISSUE TITLE
Hide preview text

### ISSUE THREAD

**Issue by Donkey-Doug** [readrops/Readrops#130]
Make it possible to hide the preview text and only show the title.

![Screenshot_20211013-014809_Readrops](https://user-images.githubusercontent.com/50382414/137044050-17db6615-da38-4e7e-89ac-6618b5d7a960.png)

**Comment by andreymal** [comment]
Hmm, I have the exact opposite problem: I want to display the preview text, but I couldn't find how to do it

<img src="https://user-images.githubusercontent.com/3236464/160729834-049e7ea6-d10c-4f4c-aff2-aec021c98378.jpg" width="180" height="320" alt="" />
