### ISSUE TITLE
Can't Scroll to End of Article on Pixel 4a (Android 12)

### ISSUE THREAD

**Issue by LuckierDodge** [readrops/Readrops#144]
For articles that exceed the vertical size of the screen on a Pixel 4a, the view does not correctly manage scrolling. Some amount of the bottom of the article is cut off. The longer the article, the larger amount of text is lost. This might be related to the 4a's unusually tall aspect ratio.

I could not replicate this issue on my Surface Duo.

**Comment by Shinokuni** [comment]
Could you test with the new 2.0 version?

**Comment by LuckierDodge** [comment]
I'm afraid I no longer have the Pixel 4a in question, and my current Pixel 7a is running Android 14, so you're probably safe to close this issue!

**Comment by Shinokuni** [comment]
Thank you for your quick answer! Maybe another time.
