### ISSUE TITLE
Unable to connect to FreshRSS

### ISSUE THREAD

**Issue by SmartPhoneLover** [readrops/Readrops#147]
Hello, I'm trying to connect to FreshRSS docker container, and I can't connect. But I got it working, using same credentials (URL, user, api pass) with an app called 'Focusreader'.

Reference for more information:
[https://forums.unraid.net/topic/40740-support-linuxserverio-freshrss/?do=findComment&comment=1076721](url)

**Comment by bhyde** [comment]
unlike most (all?) other readers Readrop is more helpful.  You do not need to enter the path, only the site.  So https://example.foo/ rather than https://example.foo/api/greader.api.

**Comment by SmartPhoneLover** [comment]
Sorry for the late reply.
I'm currently using FocusReader, and it's working perfectly.

So, you can make it as closed/solved.
