### ISSUE TITLE
Allow synchronizing a particular feed/folder

### ISSUE THREAD

**Issue by tactical-snail** [readrops/Readrops#153]
If the user pulls down or taps on the synchronize button while being in a particular feed/folder, only that feed/folder should be synchronized.

This would save time because synchronizing all together feeds takes a lot of time. And sometimes, you only want to read  from one feed/folder.

**Comment by Shinokuni** [comment]
Added in 2.0 for local accounts only. A first beta is available [here](https://github.com/readrops/Readrops/releases/tag/v2.0-beta01) if you would like so.
