### ISSUE TITLE
Current state of the project

### ISSUE THREAD

**Issue by Shinokuni** [readrops/Readrops#155]
I'm making this thread to talk about Readrops development state for those who follow the project and would be interested in some news.

I think you may have realized that Readrops development is currently very slow : no new commits, no answers to issues. etc. Indeed, I have very little time to dedicate to Readrops development, since at least the end of 2020. My current studies take all my time and I have to choose spending the little free time I have left to either work on Readrops or relax.

When I started working on Readrops in 2019, I wanted to build a full-featured app, supporting a large amount of services while being FOSS. Having big difficulties to work on this project because of my studies and other projects taking all my time, I haven't reach this goal yet. But I am not in the mood of giving up. Readrops will still continue to evolve, but as fast as I can.

Today, the goal is to release v1.4 as soon as possible with the major feature being the implementation of Fever API.

After this, I would like to spend time to work on some aspects of the app. 

First, I would like to get rid of all Readrops java code, which prevents me to evolve to a full Kotlin ecosystem. To do this, I plan to rewrite UI with Jetpack Compose. I think this will be pretty straightforward as Readrops use cases are simple and as I have worked on a little project of mine with Jetbrains Compose which is just Jetpack Compose for Desktop.

While rewriting the UI, I would also like to improve the global appearance, but as I am not a UI/UX designer, I would gracefully appreciate if some people could help me in this.

Working on 1.4, I have spent a lot of time on technical stuff like adding code coverage, improving tests and global code quality. Next, I would like to migrate to Gradle Kotlin DSL, add a linter, use Kotlin coroutines, stateflow/sharedflow, etc.

In addition to improving Readrops global reliability, synchronization speed, I would also like to make some efforts adding support for more services.

Feel free to ask anything related to this thread.

Thank you for reading.

EDIT 03/03/2023: see my message below about the upcoming 2.0.
EDIT 05/04/2024: see my last message about 2.0 release progress

**Comment by martin-desktops** [comment]
Hello, thanks for informing is!
Speaking of User Experience, I think that in times when rss feeds contains only first paragraph of the article, it would be a great choice to make "Open in browser" action easier accessible. Right now, the button is placed at the top of screen, in the right corner, making it hard to reach without changing way of grip. I would place this element next to "Add to favorites" button. I wish phones were smaller ^^

**Comment by martin-desktops** [comment]
Hello, thanks for informing is!
Speaking of User Experience, I think that in times when rss feeds contains only first paragraph of the article, it would be a great choice to make "Open in browser" action easier accessible. Right now, the button is placed at the top of screen, in the right corner, making it hard to reach without changing way of grip. I would place this element next to "Add to favorites" button. I wish phones were smaller ^^

**Comment by tunbridgep** [comment]
One of the most important user experience features for me would be the ability to mark an article unread while it's open, similar to what email clients do. Otherwise we have to go find it and mark it unread again after we close it, if we didn't get to finish reading it for whatever reason

**Comment by update-freak** [comment]
Hello,

thanks for the information.
I will use it with FreshRSS for articles as well as podcasts.
Therefore it would be nice, if you could features for podcasts like
- automatic download of podcasts when they are marked as favorite
- playlist (or a folder, e.g. "To listen later") for podcasts and saving the play progess
- playing in the background when using other apps in front (e.g. a map app in front while playing the podcast)
- Android Auto support to listen to the podcasts on car
I know there are many requirements and I'm not sure how hard it is to realise them.
For me it would be great to combine the information input (articles and podcats) to one app (Readrops) and one service (FreshRSS) instead of have the podcasts on AntennaPod as they are not synchronised (or on other not selfhosted service gpodder.net.
Thank you for your work. I love your app.

**Comment by tunbridgep** [comment]
I kind of wish ANY of the good-quality podcast apps like gPodder actually had proper support for freshrss, since they usually have very good UI/UX

But it's probably a better approach for someone to make a freshrss addon to add gPodder compatibility. That way, any good quality podcast client will work with it.

**Comment by AlerpCoder** [comment]
> Hello,
> 
> thanks for the information. I will use it with FreshRSS for articles as well as podcasts. Therefore it would be nice, if you could features for podcasts like
> 
>     * automatic download of podcasts when they are marked as favorite
> 
>     * playlist (or a folder, e.g. "To listen later") for podcasts and saving the play progess
> 
>     * playing in the background when using other apps in front (e.g. a map app in front while playing the podcast)
> 
>     * Android Auto support to listen to the podcasts on car
>       I know there are many requirements and I'm not sure how hard it is to realise them.
>       For me it would be great to combine the information input (articles and podcats) to one app (Readrops) and one service (FreshRSS) instead of have the podcasts on AntennaPod as they are not synchronised (or on other not selfhosted service gpodder.net.
>       Thank you for your work. I love your app.

I would recommend you to use a podcast catcher and not an rss reader

**Comment by AlerpCoder** [comment]
Hi it is nearly the End of the Year and i would like to redo the frontend, I don't really care about the language I use but this app is my daily driver. @Shinokuni do you still want to work on this?

**Comment by Shinokuni** [comment]
Hello, yes, I am still willing to work on Readrops, I have been working on another project who has taken most of my free time and I would like to finish a first version before coming back to Readrops.

I plan to rewrite the UI with Jetpack Compose, so feel free to propose mockups if you would like to.

**Comment by lucyferu** [comment]
> the major feature being the implementation of Fever API

i came here to check if there was a way to connect my miniflux account to this app (which is my fave android one so far!) and i guess that is the answer?
if so, can't wait for this release to come!


> the ability to mark an article unread while it's open

this would be a very handy implementation as well!


said that, thank you very much for what you did and what you're doing.
i wish you all the best on your studies and your other project and i hope to read good news about this one anytime soon!

**Comment by Shinokuni** [comment]
I am making this very quick message to notify that I have started working on the 2.0 version of Readrops. I attempted to work on 1.4 when I had free time, but I had really little motivation. Instead, I have decided to move straight to the development of 2.0 which will include among other things a complete rewrite of the UI, which I found way more motivating. Feature set isn't fixed yet, so I am still open to suggestions.

**Comment by lucyferu** [comment]
personally, adding

- implementation of Fever API;
- the ability to mark an article unread while it's open;

would make this app my dream app. 💟

**Comment by hardwareadictos** [comment]
> I am making this very quick message to notify that I have started working on the 2.0 version of Readrops. I attempted to work on 1.4 when I had free time, but I had really little motivation. Instead, I have decided to move straight to the development of 2.0 which will include among other things a complete rewrite of the UI, which I found way more motivating. Feature set isn't fixed yet, so I am still open to suggestions.

Feel free to contact me if you need a tester :)

**Comment by update-freak** [comment]
I'm not sure if the current version have all these functions, but for me the following would be great to have
- dark theme (automatic switch from light to dark and back via system theme)
- Mark as read when I scroll over new unread feed
- possible to mark favorites with are synced with freshrss
- very fast (instant) sync with freshrss
- unread counter
- share possibility with Yatse (Kodi) for video files (maybe build in video player)

Thanks a lot for your great app!

**Comment by vdbhb59** [comment]
@Shinokuni I am available for testing and any help you need. 👍

**Comment by daffydock** [comment]
Hi @Shinokuni, 
I used to use your app a few years ago and as chance would have it, decided to take a loot at it again, since a while ago I started hosting a FreshRSS instance on top of an existing Nextcloud News one. There has not been any new releases in a while and I know why, you have been transparent, are busy, and clearly, I fully understand that. 

Was just wondering what do you have in mind with the project. I can see in Actions that you have been active pushing changes as of late, and although I am not asking for any dates in specific, I was wondering about what you had in mind in terms of general schedule, out of sheer curiosity since the last post on this topic was about 7 months ago. Any info you opt to share would be appreciated. 
It is a great app and fairly unique in the Android space.  

Cheers.

**Comment by Shinokuni** [comment]
Thank you for your message @daffydock! It is true I had a hard time finding the right work pace but since the beginning of 2024, I have been able to work on Readrops on a pretty regular basis.

About the next major release, I am very regarding on the quality. I haven't decided yet about all the features which should land in the 2.0 release, but I hope being able to release at least a beta version in July of this year.

Currently, I have been working on the total rework from zero of the UI which is in a good progress state. I would like to get rid of all java code and its associated dependencies (rxjava...) which implies to also rewrite large API logic implementations.

I always wanted for Readrops to be a standard for Android RSS aggregators. I hope with this release to get a bit closer.

**Comment by Shinokuni** [comment]
Hello folks,

I would like to provide some information about Readrops 2.0 progression state. Since my last comment, I have been able to keep working regularly and the project keeps getting better, 2024 will definitely be the revival of Readrops!

So here is the progression:
- New UI is done at 90%, but needs polishing
- Project is near reaching feature parity with the old v1.3
- Local, FreshRSS and Nextcloud News accounts do work with almost all their respective features, but some details still need to be improved
- On the technical side, I have been able to get rid of all java code, replace RXJava by coroutines, rewrite API implementations and repositories in kotlin, migrate Gradle build files to kotlin dsl and more

I planned to release a first beta release in July, but with the current progression state, it would be more reasonable to target the beginning of August.

**Comment by Shinokuni** [comment]
Hello people,

Here is the august update! I've just merged the FEVER API dev branch into develop which is now ready to use. This was the last real feature for 2.0. I'm going to concentrate now on a bit of polish, here is what's left to do:

- Test FEVER API with another provider than FreshRSS
- Add a splash screen the right way
- polish a bit the article screen
- rework app colors
- minor fixes here and there

If everything is all right, I should be able to ship the first beta at the end of the week or at the beginning of next week. I also need to find a way to install the beta version along the current stable one.

**Comment by vdbhb59** [comment]
> I also need to find a way to install the beta version along the current stable one.

Different signature, or appname (com...).

**Comment by w1n5l0w** [comment]
> Test FEVER API with another provider than FreshRSS

If you like, I can give you @Shinokuni  an account on my Miniflux-Server. Just comtact.me, if this helps.

**Comment by Shinokuni** [comment]
@w1n5l0w I would really appreciate if you can do this! You can send all the info by email (my profile email, no credentials in plain email of course) as I've just discovered there is no DM system in Github, thank you very much!

**Comment by w1n5l0w** [comment]
Hi @Shinokuni , I just wrote you an email for the Miniflux-Account.

> I also need to find a way to install the beta version along the current stable one.

Maybe it is an option to use the work profile of Android to install beta along stable version. There are [Shelter](https://f-droid.org/de/packages/net.typeblog.shelter/) (I am using this) and [Insular](https://f-droid.org/de/packages/com.oasisfeng.island.fdroid/) on F-Droid which enable the management of the work profile.

**Comment by Shinokuni** [comment]
Hello people, 2.0 first beta is out! It has been a long journey since the first post of this topic and the upcoming 2.0 will be a new start after three years of inactivity.

 I would be very grateful if you could test it and report any bug you could find. The apk is safe to install along any stable version.

@w1n5l0w I succeeded by simply adding a new build type inheriting from the release one and using debug signing.

**Comment by hardwareadictos** [comment]
Testing 2.0, Will report back if I found something broken. Thanks a lot for the hard work! New UI is beautiful 👏🙂

**Comment by vdbhb59** [comment]
Already trying, being 3rd day now. Other than some lagging and few times breaking the app seems to be fine for now. I am trying with few pages which do not have auto rss, but I use my rssbridge instance to generate and be able to read them through the fever api. As of 3 hours ago, I have had no issues.
Will report back if anything does come up.
