### ISSUE TITLE
Unable to remove favorites

### ISSUE THREAD

**Issue by wj25czxj47bu6q** [readrops/Readrops#156]
Once a favorite is added, it is impossible to remove. The floating button changes from a solid star to a hollow star as expected, but the article stays in favorites even after closing and relaunching the app (floating button goes back to a solid star). I even tried Force Stop and Clear Cache which did not help.

I am using a local account, if it matters. Read later and read/unread toggles work fine.

**Comment by Shinokuni** [comment]
This should be fixed in the new [2.0 version](https://github.com/readrops/Readrops/releases) as the UI has been entirely remade.
