### ISSUE TITLE
Expecting END_OBJECT issue

### ISSUE THREAD

**Issue by mbnoimi** [readrops/Readrops#162]
First of all I'd like to thank you a lot for the greate project.

Whenever I try to connect Readrops with my FreshRSS service I get this error message:
```
Expected END_OBJECT but was NAME at path $.item[0].alternate[0].href
```

Is there anything wrong with my service configuration or what?

- https://github.com/FreshRSS/FreshRSS/commit/e27eb1ca9198119ea1b0bd79be5f1aead45d615a
- [Readrops](https://github.com/readrops/Readrops): 1.3.1 (14)
- My service located in: https://top.mydomain/p/
- [FreshRss Android Client](https://gitlab.com/christophehenry/freshrss-android) works fine.

![image](https://user-images.githubusercontent.com/284547/185069588-d2fa82a0-25f3-4269-abc7-137c76711a4f.png)

**Comment by jimbudarz** [comment]
I'm getting the same error, but for context I also just changed my Fresh RSS container in a few ways
- Switched from linuxserver.io's FreshRSS Docker container to the official
- Switched to the FreshRSS edge branch from latest
- Switched from HTTPS connection to the container to HTTP via reverse proxy from external HTTPS request.

**Comment by Alkarex** [comment]
It looks like a bug in:

https://github.com/readrops/Readrops/blob/8a5fae5411420a135162143d7e279157dc17555c/api/src/main/java/com/readrops/api/services/freshrss/adapters/FreshRSSItemsAdapter.kt#L85-L102

the response might contain:

```json
	"alternate": [
		[
			"href": "https://example.net",
			"type": "text/html"
		]
	]
```

The line `"type": "text/html"` was not always provided before.

In any case, additional key-values should not break the parsing.

**Comment by Alkarex** [comment]
Patch suggestion (not tested - no compile environment set up) https://github.com/readrops/Readrops/pull/163

**Comment by Alkarex** [comment]
Workaround https://github.com/FreshRSS/FreshRSS/pull/4568 while waiting for above Readrops fix to be tested and merged.
