### ISSUE TITLE
Old articles on top

### ISSUE THREAD

**Issue by Tealk** [readrops/Readrops#168]
Hello,

I use the app in conjunction with Freshrss and have the problem that old posts are displayed at the top:
![Screenshot_20230214-091334.png](https://user-images.githubusercontent.com/12276250/218677879-ec3df6d2-2044-424c-a4e2-9fb0ce364b86.png)

**Comment by Shinokuni** [comment]
The two first articles at the top aren't technically the oldest but the newest. If you take 14/02/2023 as reference date, 06/12/2023 is newer. There is not much you can do except delete the relevant feed. This happen sometimes for some badly managed feeds.
