### ISSUE TITLE
Mark All as Read Doesn't Work

### ISSUE THREAD

**Issue by bmreading** [readrops/Readrops#169]
I'm seeing an issue, where FreshRSS feeds are not updated when trying to mark all as read. I have not yet tested this out with any other sort of articles.

FreshRSS v1.19.0-dev
Readrops v1.3.1 (14)

Here are the steps to reproduce:

1. Using FreshRSS account, navigate to a category with unread articles.
2. Tap and hold an article in the list to activate multi-selection mode.
3. Tap the "select all" icon.
4. Tap the "mark as read" icon next to it.
5. At this point, all articles in the list appear grayed-out. However, any refresh of feeds or synchronization brings them all back to unread.

**Comment by Patriot2407** [comment]
+1

**Comment by Patriot2407** [comment]
I have found that if 30 or more articles are selected, and then marked as read, it doesn't work, but 29 or less does. Maybe this helps?

**Comment by Shinokuni** [comment]
This should be fixed in the new [2.0 version](https://github.com/readrops/Readrops/releases) as the UI has been entirely remade.
