### ISSUE TITLE
OPML import error

### ISSUE THREAD

**Issue by mikhirev** [readrops/Readrops#173]
Hi!

I'm trying to import OPML created by Flym but get a error. 

![Screenshot_20240131-152314](https://github.com/readrops/Readrops/assets/1032317/8bd831c1-362f-4b44-895f-4ef80a1884b9)
![Screenshot_20240131-152218](https://github.com/readrops/Readrops/assets/1032317/b9a3815a-9e1e-483b-941f-c75f93e106d6)

**Comment by mikhirev** [comment]
Added sample file triggering the error:
[Flym_min.opml.txt](https://github.com/readrops/Readrops/files/14111678/Flym_min.opml.txt)

**Comment by Shinokuni** [comment]
Your sample works with the upcoming 2.0. A beta version is available to try.
