### ISSUE TITLE
Release on Google Play and update F-droid version

### ISSUE THREAD

**Issue by JosephChataignon** [readrops/Readrops#175]
It looks like Readrops is not available in Google Play anymore, the button in the Readme file leads to a 404 error.
The link to F-Droid works, but that version hasn't been updated in 3 years.

**Comment by Shinokuni** [comment]
Google Play version not being available is because the app page needs to meet some requirements I didn't care of.

The f-droid version is the most recent one. No updates have been made since. I am currently working on a 2.0, maybe I should write it on the README.

**Comment by Offerel** [comment]
Are there any timelime for a beta or downloadable apk?

**Comment by Shinokuni** [comment]
I put some updates related to 2.0 advancement in #155. I currently target August for a first beta.

**Comment by Shinokuni** [comment]
The Google Play page has been restored. v2.0 is currently in its beta phase, but should come out soon.
