### ISSUE TITLE
Item size dialogue not auto-confirming

### ISSUE THREAD

**Issue by talkingseedling** [readrops/Readrops#185]
In version 2.0beta01, when selecting "item size" in settings, selecting a radio button doesn't close the dialogue window, so the user needs to click "cancel". "cancel" however doesn't cancel the operation, but successfully confirms the users selection.

**Comment by Shinokuni** [comment]
That's a translation confusion, it should be "Back" instead of "Cancel", thanks for reporting!

**Comment by Shinokuni** [comment]
Fixed in e0fcf26.
