### ISSUE TITLE
FreshRSS accounts don't work under 2.0-beta01

### ISSUE THREAD

**Issue by sevmonster** [readrops/Readrops#186]
![blur1724863013593](https://github.com/user-attachments/assets/9e89e2f3-3206-474c-9b20-8e25ec8e90e3)

Android 14, GrapheneOS

**Comment by talkingseedling** [comment]
I'm currently hosting freshrss with docker with watchtower, so freshrss is the latest version, and don't have this issue with 2.0beta01. Are you specifically using sub folders to self host at /api? What happens when you remove the /api?

**Comment by sevmonster** [comment]
It does indeed work without it, you're right. But I swear this is how I configured it before the beta...
