### ISSUE TITLE
[Feature Request] Restore Swipe-to-mark-as-read

### ISSUE THREAD

**Issue by Faeranne** [readrops/Readrops#188]
Many of the feeds I follow share both things I'm interested in, and articles I know I am not interested in.  For instance, the Adafruit blog shares new products, blog entries, and videos.  I am rarely interested in new products, and just swipe them away, but am very interested in the blog entries and sometimes the videos.  I would "cull" my list first, then read through things after.

**Comment by johnolinda** [comment]
Agreed. I feel like this feature, or something similar like long-press to mark as read, is pretty essential for processing feeds.

**Comment by Shinokuni** [comment]
I didn't keep this feature as I added the read on scroll one: mark read articles when they disappeared from the top of the screen. I think it might suit your use case. Could you test it?

**Comment by johnolinda** [comment]
Read-on-scroll definitely works for some people, but my workflow involves skimming through to eliminate anything that's obviously not of interest and then going back to process the things I want to read. I don't process my feeds chronologically until after I have made that initial pass.

**Comment by Shinokuni** [comment]
Ok so I planned not to add new features while Readrops being in beta, but as it's about restoring an already existing feature, I guess it's fine. Added in c31a0cde20ae13c448ac10686c71c506196f03c0, will be available in the next beta. Currently only right to left swipe is enabled to mark items read/unread, but customization will come.
