### ISSUE TITLE
OPML Import not working in 2.0-beta02

### ISSUE THREAD

**Issue by Shinokuni** [readrops/Readrops#195]
Hello, I'm using Readrops version 2.0-BETA02 from F-Droid.
It doesn't let me pick the opml file exported from [AniVu](https://f-droid.org/packages/com.skyd.anivu/) from my file manager or even from default FM (`com.android.documentsui`)

```
<?xml version='1.0' encoding='UTF-8' ?>
<opml version="2.0">
  <head>
    <title>AniVu</title>
    <dateCreated>Sat Sep 07 14:16:03 GMT+05:30 2024</dateCreated>
  </head>
  <body>
    <outline htmlUrl="https://f-droid.org/feed.xml" text="F-Droid - Free and Open Source Android App Repository" title="F-Droid - Free and Open Source Android App Repository" xmlUrl="https://f-droid.org/feed.xml" />
    <outline htmlUrl="https://news.nononsenseapps.com/index.atom" text="Feeder News" title="Feeder News" xmlUrl="https://news.nononsenseapps.com/index.atom" />
  </body>
</opml>
```

_Originally posted by @shuvashish76 in https://github.com/readrops/Readrops/issues/41#issuecomment-2335122776_

**Comment by Shinokuni** [comment]
Could you give me the file mime type and its full name? Otherwise the content you gave me works with Readrops. By default, Readrops looks for text/xml files.

**Comment by shuvashish76** [comment]
> By default, Readrops looks for text/xml files

It's an `.opml` file : 
[AniVu_08-Sep-2024 10259 AM_1018288426.opml.zip](https://github.com/user-attachments/files/16919721/AniVu_08-Sep-2024.10259.AM_1018288426.opml.zip) (_GitHub doesn't support ompl uploads sending as zip)_

**Comment by hjek** [comment]
`.opml` files are greyed out in the file selector. When extension is changed to `.xml` they're selectable (but still cause error on import, at least the OPML exported from Feeder and from Caly).

**Comment by Shinokuni** [comment]
Okay for a reason I don't understand, Android treats opml files as binary files and not text files. Currently the file mime/type filters given to the file picker are: `application/xml`, `text/xml`, `text/x-opml`. But Android returns `application/octet-stream` for an opml file. As I would like to exclude as much file types as possible, I will only add `application/octet-stream` to the current filters hoping it's enough to include opml files.

@hjek As stated in #194, Feeder uses an opml format currently not supported by Readrops. It might also be the case for Capy.
