### ISSUE TITLE
Sync favorites with nextcloud

### ISSUE THREAD

**Issue by teemue** [readrops/Readrops#199]
Everything works fine when using nextcloud sync besides syncing of favorite/starred items 🙂

**Comment by Shinokuni** [comment]
Could you share some more info:
- What app version?
- What is the problem exactly? Are starred items not fetched at first sync? Or is this a syncing problem between Readrops and your instance afterwards?

**Comment by teemue** [comment]
They weren't fetched at all. I reinstalled the app and now it's working.
