### ISSUE TITLE
[Bug] なんで「フィード処理エラー」と出てくるのかわからない

### ISSUE THREAD

**Issue by Tpaefawzen** [readrops/Readrops#221]
**Describe the bug**
正しい内容のRSS 2.0のはずですがうちのRSSで「フィード」→「フィードを追加」で私のURLリンクを貼り付けて「確認」ボタンを押したら「フィード処理エラー」でできなかったです。

https://raw.githubusercontent.com/Tpaefawzen/tpaefawzen.github.io/27d7aef1a0c9155cdff7165fd7c88c2dcfb6a5d0/tubuyaki.xml

**To Reproduce**

**Expected behavior**

**Environment information (please complete the following information):**
 - Account type: Local
 - App version: v2.0
 - Android version: Android 10
 - Device type: [e.g. One Plus 12, Samsung Galaxy S23]
 - Store: [e.g F-Droid, Play Store, standalone apk]
 - [ ] Stacktrace collected from crash screen

**Additional context**

スタックトレースありません

**Comment by Shinokuni** [comment]
I would be grateful if you could use English when opening an issue.

Your feed seems bad formatted: all items miss the `<link>` tag, which is used in Readrops as a unique key. Without it, there is a high chance to have conflicts between items if we had to rely on `<title>` or `<description>` tags.
