### ISSUE TITLE
[Bug] Image download

### ISSUE THREAD

**Issue by talkingseedling** [readrops/Readrops#226]
**Describe the bug**
Downloading an image provides the pop-up "image download" but I can't find it afterwards.

**To Reproduce**
1. Long hold an image, click download.

**Expected behavior**
The image is downloaded to a location any standard gallery app would detect.

**Environment information (please complete the following information):**
 - Account type: Freshrss
 - App version: 2.0.1
 - Android version: Android 14
 - Device type: Samsung Galaxy A52
 - Store: Obtanium,github

**Additional context**
Readrops doesn't ask for files permission

**Comment by Shinokuni** [comment]
Fixed in b803058210193acb8044fade1e48e86b43b00e7e.
