### ISSUE TITLE
[Bug] Error parsing yarr fever API feeds response

### ISSUE THREAD

**Issue by fenuks** [readrops/Readrops#228]
**Describe the bug**
[yarr](https://github.com/nkanaev/yarr) is a server with [fever API support](https://github.com/nkanaev/yarr/blob/master/doc/fever.md). Its fever implementation seems to be correct, and it works with [NewsFlash](https://gitlab.com/news-flash/news_flash_gtk/) and [Read You](https://github.com/Ashinch/ReadYou).

Trying to fetch/refresh feeds yields `JsonDataException` with message `Expected BEGIN_ARRAY but was NUMBER at path $.last_refreshed_on_time`. As I understand, assumption that the first three fields of the feeds response are `api_version`, `auth`, `last_refreshed` [made here](https://github.com/readrops/Readrops/blob/db04cdddb7da23662d2a8fe0ff29b655b668b78f/api/src/main/java/com/readrops/api/services/fever/adapters/FeverFeedsAdapter.kt#L35) is incorrect. In general, assuming any order doesn't seem like a good idea. In case of yarr, field order is different:

```json
{
	"api_version": 3,
	"auth": 1,
	"feeds": [],
	"feeds_groups": [],
	"last_refreshed_on_time": 1731858050
}
``` 

**To Reproduce**
Steps to reproduce the behaviour:
1. Add yarr account (default URL is `http://my_ip:7070/fever/`), by default auth is not enabled, so any login/password combination will work
2. Tap refresh feeds button
3. See error

**Environment information (please complete the following information):**
 - Account type: Fever
 - App version: 2.0.1 (also tested app built from the latest git version, namely [db04cdd](https://github.com/readrops/Readrops/commit/db04cdddb7da23662d2a8fe0ff29b655b668b78f))
 - Stacktrace collected from logcat
 ```
Caused by: com.readrops.api.utils.exceptions.ParseException: Expected BEGIN_ARRAY but was NUMBER at path $.last_refreshed_on_time
  	at com.readrops.api.services.fever.adapters.FeverFeedsAdapter.fromJson(FeverFeedsAdapter.kt:94)
  	at com.readrops.api.services.fever.adapters.FeverFeedsAdapter.fromJson(FeverFeedsAdapter.kt:19)
  	at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:46)
  	at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:27)
  	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:246)
  	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:156)
  	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
  	at java.lang.Thread.run(Thread.java:920)
```

**Comment by Shinokuni** [comment]
Indeed, you're right, I fixed this behavior in `FeverItemsAdapter`, but not in `FeverFeedsAdapter`, thanks for reporting! A fix will be available in the next version.

**Comment by Shinokuni** [comment]
Fixed in d2dff633e1a2d68b6882b83762db9beff550d336.

**Comment by fenuks** [comment]
Thank you for the quick fix!

Are you certain that this will work for any order of fields? I don't know how exactly Reader works, but it seems to me that now parser expects that `feeds` field goes first, then `feed_groups` – so order still matters, just differently. When I moved `feed_groups` before `feeds` in `api/src/test/resources/services/fever/feeds.json`, parsing test failed.

**Comment by Shinokuni** [comment]
Once again you're right... I applied `FeverItemsAdapter` logic on `FeedsItemsAdapter` without much thought and now I realize that some other Fever adapters use the same wrong logic.

Could you test out the fix which is available in 2.0.2 (currently available in the play store and standalone apk in release page)? I'm now not so confident about it. If it doesn't work, I'll make a new fix with the right approach in a new release, otherwise this could wait 2.1.

**Comment by fenuks** [comment]
Sure, I'll check it. I don't have phone with gapps, but a standalone apk will do.

**Comment by fenuks** [comment]
I've checked the new version, and app can now process `feeds` response, but fails to parse `favicons` response in `FeverFaviconsAdapter` – error is analogous to fixed one, parser assumes specific fields order. Probably there will be more errors in other response adapters.

yarr responds (favicon data skipped for brevity):
```json
{
	"api_version": 3,
	"auth": 1,
	"favicons": [],
	"last_refreshed_on_time": 1732118750
}
```

In case you would like to check it yourself, it's very easy to get yarr working. It is statically linked executable and uses sqlite, so simply running `yarr` without any arguments is sufficient. URL to fever API is given in the opening post of this issue.

**Comment by Shinokuni** [comment]
Yeah this is what I feared. So I took the time to check each adapter and fix it properly.

I am now trying to test yarr, but I cannot reach its API end point, so I wonder how you were able to at least login with Readrops. I get a 404 error with `http://ip_addr/fever/?api`. Did you setup something to make it work?

**Comment by fenuks** [comment]
You need to put exactly `http://your.ip.addr/fever/`. Slash at the end is required, otherwise yarr will return 404. Do not add `?api`.

**Comment by Shinokuni** [comment]
Sadly this didn't change anything. I posted something [here](https://github.com/nkanaev/yarr/discussions/225#discussioncomment-11422689) in a yarr discussion, we'll see if we got some answers. 

Otherwise it seems that #229 has the same problem with Readrops Fever implementation. I will try testing with a Tiny-Tiny RSS instance and if it works, I will consider yarr compatibility fixed as well.

**Comment by fenuks** [comment]
Perhaps there is no stable version with fever, last release is from previous year. Mine is built from git head, because I host my yarr instance on OpenWRT router, and have to cross-compile it.

TT-RSS has fever integration, but as third-party plugin (prior to yarr, I've been using TT-RSS, but only via its built-in web UI).

**Comment by Shinokuni** [comment]
You're fully right, that's why I couldn't make Fever with yarr works. Built a version from master and it works! Not sure however if Fever is fully implemented, read state sync works but not star state. Anyway, this is another problem.

The fix will be available in the next bug fix version.

**Comment by fenuks** [comment]
I'm glad I could help!

Out of curiosity, why do you parse JSON by hand, instead using library like
jackson or gson that can deserialize JSON response to given class? They require much less code, and are less error prone, because these libraries are battle-tested and one can assume that if response is correct, then one will get class instance regardless of field order, etc.

**Comment by Shinokuni** [comment]
Your suggestions are totally valid as I think there isn't one way to do things! 

One more thing to add for those libraries: heavily relying on annotations to do work could be likened to an embedded weak mini-language. Therefore I don't think those would be easier to write and understand than directly using the language itself. I highly recommend you this [blog post](https://blog.softwaremill.com/the-case-against-annotations-4b2fb170ed67) which goes down further about annotations.
