### ISSUE TITLE
New Logo for Readrops

### ISSUE THREAD

**Issue by Yasujizr** [readrops/Readrops#26]
Hi, 

I'm doing logo for open source projects. When I was doing research at Github, I saw your project. If you want, we can design a logo according to your wishes.

cheers.

**Comment by Shinokuni** [comment]
Hi,

Welcome and thank you for your proposal !

It would have been a pleasure but I already have someone in charge of the app icon design.

**Comment by Yasujizr** [comment]
Thank u.
Good Luck for the app. 

Cheers.
