### ISSUE TITLE
[UI Improvement] Avoid Keyboard Overlap EditText

### ISSUE THREAD

**Issue by Kcchouette** [readrops/Readrops#30]
When registering a nextcloud news account, when the keyboard appears, it covers all the 2nd-part-of-screen edittext.

The goal of this issue is to avoid that.

**Comment by Shinokuni** [comment]
Fixed in 2.0. The first beta is [available](https://github.com/readrops/Readrops/releases/tag/v2.0-beta01) to test if you would like so.
