### ISSUE TITLE
[Keyboard Improvement] Have the (next) button in the bottom right of the android keyboard

### ISSUE THREAD

**Issue by Kcchouette** [readrops/Readrops#31]
When registering a nextcloud news account, focusing and finishing editing the URL.

I would be a better UX to have the (next) button in the bottom right of the android keyboard (so to have this keyboard:

![](https://user-images.githubusercontent.com/3000936/63809820-986f9a80-c923-11e9-8136-0de3a24b7102.png)

to automatically switch to username edittext)

**Comment by Shinokuni** [comment]
Fixed in 7920e54fbc251c730ca9c204c34d4559e916590c
