### ISSUE TITLE
[UI bug] Disparition of the "Add account" button

### ISSUE THREAD

**Issue by Kcchouette** [readrops/Readrops#33]
Here how I've done it:

1. I have a NextCloud News account
1. I create a local account (using the "Add account" button)
1. See you have the possibility to create a new one (using the "Add account" button)
1. Delete your local account
1. The apps switch to your nextcloud news account (it's normal)
1. But you don't have anymore the "Add account" button

Closing and restarting the apps permit to have again this "add account" button

**Comment by Shinokuni** [comment]
Thank you, this is fixed since e5c8e82
