### ISSUE TITLE
F-droid as a source

### ISSUE THREAD

**Issue by nr458h** [readrops/Readrops#40]
Hi, 
thanks for your work. As there are people like me trying to avoid google wherever I can. It would be great if we would support fdroid as well. If your fine with this idea I would open a request on f-droid.org

Thanks in advance

**Comment by Shinokuni** [comment]
Hi,
Thanks for your interest in Readrops. I have already opened a merge request on f-droid repository 4 months ago. You can find it [here](https://gitlab.com/fdroid/fdroiddata/merge_requests/5422). 

However, I don't really know why it hasn't been merged since.

**Comment by linsui** [comment]
It's available in F-Droid now. You can add a [badge](https://f-droid.org/badge/get-it-on.png) in Readme. 😄

**Comment by nr458h** [comment]
Congrats to @Shinokuni ;)

And thanks for the quick response

**Comment by Shinokuni** [comment]
Thank you for your help @nr458h !
