### ISSUE TITLE
Fastlane improvements

### ISSUE THREAD

**Issue by IzzySoft** [readrops/Readrops#43]
To make your description render correctly on F-Droid, you could use HTML tags in your `full_description.txt`:

```html
<p>Readrops is a multi-services RSS feed client.<br></p>
<p><b>Features:</b></p>
<ul>
  <li>Local RSS parsing
  <li>RSS 2.0, ATOM and JSON formats support
  <li>Multiple accounts
  <li>Feeds and folders management (create, update and delete feeds/folders if your service API supports it)
  <li>Nextcloud News support
  <li>FreshRSS support
</ul>
<p>Other features will come in the near future.</p>
```

**Comment by Shinokuni** [comment]
Year, you are right, thank you. 

Do you know if Markdown support is planned ?

**Comment by IzzySoft** [comment]
I guess not, at least not in the foreseeable future. IMHO HTML is the lowest common denominator; must be compatible with more than just F-Droid, as Fastlane was primarily written for Google Play AFAIK. Further, if you want to permit multiple standards, you must be able to detect them – which adds more complexity.

**Comment by Shinokuni** [comment]
I see.

I would have one last question, do you know which of those three images, featureGraphic, promoGraphic and tvBanner F-droid uses as banner ?

**Comment by IzzySoft** [comment]
To my knowledge: featureGraphic.

**Comment by Shinokuni** [comment]
What I thought.

A big thanks for your help!

**Comment by IzzySoft** [comment]
Gladly! Looking forward to the next release then :smiley:
