### ISSUE TITLE
[Feature request] Automatically mark articles as read

### ISSUE THREAD

**Issue by sugarhd** [readrops/Readrops#45]
Please, is it possible to add this option that enables marking articles as read automatically while you scroll article list.

Or, firstly, just add the possibility to mark a feed or an entire folder of feeds as read.

Thx!

**Comment by Shinokuni** [comment]
Hello, thank you for using Readrops !

> Please, is it possible to add this option that enables marking articles as read automatically while you scroll article list.

Yep, sounds possible.

> Or, firstly, just add the possibility to mark a feed or an entire folder of feeds as read.

It is possible to do so for feed or all items. Just long press an item, and use the menu actions (select all and mark as read/non-read).

**Comment by toketin** [comment]
Hi, I join to this feature request, I find very useful the possibility to mark as read on scrolling the article list.

**Comment by lebochequirit** [comment]
+1 for this feature from me. This is what keeps my tied to TT-RSS although I'd like to drop it.
If you have >10 Feeds in your timeline, you get a Phone thumb only by tapping what you don't want to read ;-)

**Comment by Torenga** [comment]
> It is possible to do so for feed or all items. Just long press an item, and use the menu actions (select all and mark as read/non-read).

Thank you @Shinokuni, I couldn't understand how to mark feeds as read and came here to post a request issue. I suggest it's more obvious for new users or even have a dedicated button on the top bar.

I really enjoy using the app so far, thank you!

**Comment by uraza** [comment]
+1, it would be very useful to have a way to have a way to mark all articles as read.

**Comment by smellymoo** [comment]
+1 this is the major UE issue. I would put it above all else.

**Comment by GiTimm** [comment]
+1

**Comment by Shinokuni** [comment]
This feature was added in 11f87d14a5f8ab5ce349019c2bd01db2861cb645 as a parameter, disabled by default. It will be available in 1.4.
