### ISSUE TITLE
Readrops does not show old articles

### ISSUE THREAD

**Issue by deadwax** [readrops/Readrops#52]
I'm using Readrops with NC news. Older items that show in the web interface on NC do not show up in Readrops, whether or not they are read.

An example is floweringelbow.org. In NC all posts show in the news app, in Readrops none do. I can't work out why.

Readrops 1.1.3(9) from fdroid

**Comment by Shinokuni** [comment]
When you setup your NC News account, Readrops gets the last 5000 unread items.

I checked `floweringelbow.org` and the last article was published the 2019-06-04. So It's possible if you have a significant number of feeds which produce many items and you don't often read them, that `floweringelbow.org` items won't be included in the unread items fetch.

**Comment by deadwax** [comment]
This seems unlikely, I don't have many feeds in NC at this stage and Readrops is displaying only 31 articles total. It should be displaying far more than that, the NC web interface displays 216 unread and many more read.

I have Readrops set up to display read articles, so many more should be visible I would have thought.

**Comment by deadwax** [comment]
OK, I cleared all app data and logged back in. Readrops now shows 280 articles, but not any marked as read in NC.

So there is at least a caching problem and it doesn't pull read articles, though this may be related to the issue a few days ago, which is now closed?

**Comment by Shinokuni** [comment]
>OK, I cleared all app data and logged back in. Readrops now shows 280 articles, but not any marked as read in NC.

When syncing for the first time, Readrops doesn't fetch read items.

> So there is at least a caching problem and it doesn't pull read articles, though this may be related to the issue a few days ago, which is now closed?

The fact that you had to clear app data and relogin to get all unread articles is indeed weird. To try to reproduce, I will need some new accounts with just a few feeds as mine has more than 5000 unread items.

**Comment by deadwax** [comment]
> When syncing for the first time, Readrops doesn't fetch read items.

Does it ever fetch read items? I would like it to but I can't find a way to make it do it. In fact my preferred way of working would be to ignore the read status of articles when syncing and simply show x number of articles, read or not. That's what I'd expect "show read articles" to do.

> The fact that you had to clear app data and relogin to get all unread articles is indeed weird. 

In thinking further about this, it may be that I had a large number of read articles when I first logged in, from a feed I then deleted. Readrops may only check for the 5000 unread items once at login and not at any other point?

**Comment by Shinokuni** [comment]
> Does it ever fetch read items?

It does, but not when syncing for the first time.

> In thinking further about this, it may be that I had a large number of read articles when I first logged in, from a feed I then deleted. Readrops may only check for the 5000 unread items once at login and not at any other point?

Yes, that is the current behavior. There are two types of synchronization : 
- Initial synchronization : Readrops gets feeds, folders and the last 5000 **unread** items
- Classic synchronization : Readrops gets new, deleted, updated feeds and folders, new unread items and read items, and pushes items read state

NB : this works for NC News only. Currently, Readrops doesn´t get read state from FreshRSS, it pushes only.

**Comment by deadwax** [comment]
Ok, that's starting to make sense.  I don't believe classic synchronisation of read items is working on NC though - it is impossible to get it to sync any read items marked as read outside Readrops.

**Comment by Shinokuni** [comment]
v1.1.3 has a fix for NC News read state syncing, so you should have your read items synced with Readrops.

I will test again to be sure.

**Comment by deadwax** [comment]
Thanks.  Let me know if you need another NC account.

**Comment by deadwax** [comment]
Readrops still does not display articles marked as read in NC, either on first or subsequent syncs.

The News interface in NC displays them, but I have no way of showing them in Readrops.

Example of a feed with two unread articles:
In News these articles are shown among 12 other read articles.
Readrops will only show the 2 unread, refreshing does nothing.

Readrops 1.1.4 from fdroid
NC 18.0.3
News 14.1.3

**Comment by Shinokuni** [comment]
Sorry, I forgot to work on this issue. I will try to reproduce.

**Comment by SecT0uch** [comment]
Hey @Shinokuni getting read state from FreshRSS would be fantasctic !
That would be the go-to Android app for FreshRSS.

Thanks for your work!

**Comment by keunes** [comment]
@SecT0uch @Shinokuni I guess read status sync for FreshRSS would deserve it's own issue, given that this one is mainly about the read status sync with NC not working fully as expected?

**Comment by Shinokuni** [comment]
Read state sync for FreshRSS is on its way, I will be available in 1.3, so no need to create a separate issue.
