### ISSUE TITLE
Sync read later / starred articles

### ISSUE THREAD

**Issue by Alkarex** [readrops/Readrops#53]
Hello,
I have tested your nice client today, and it looks very good already, congrats :-)
In the Google Reader API (implemented by FreshRSS), there is the concept of starred articles, which are well mapping with your "read later" concept. It would be nice to sync them, i.e. retrieve the list of starred articles to show in your "read later", and the other way around.
Feel free to ask if I can provide any documentation.
Alkarex, from [FreshRSS](https://github.com/FreshRSS/FreshRSS)

**Comment by Shinokuni** [comment]
Hello,

Thank you!

Starred articles are planned but I am not sure if I should replace read later items by starred items.

**Comment by notarobot63** [comment]
Hello,
This is really the feature I'm waiting for. I use FreshRSS and I'd love to sync my starred articles.

**Comment by Alkarex** [comment]
I am preparing a table overview of clients compatible with Google Reader API https://github.com/FreshRSS/FreshRSS/pull/2942 (help welcome)
I would love to give a ✔️ to Readrops on that precise feature ;-)

**Comment by Shinokuni** [comment]
Finally, starred/favorites items are here with cfa764e78bfd6120f25932b1c48975b80cbf1ce2 and will be available in 1.3! Sorry for the delay, it was about time.

@Alkarex Working with starred articles made me work again on item read state synchronization which is still not supported for FreshRSS in Readrops. I discovered some SQL constraints (like the limitation of arguments in a request with an IN operator) which means an evolution of the db schema would be potentially required. And to keep synchronization as fast as possible, I think several limitations on the `items/ids` request are required with an optimization of some SQL requests along with the db schema evolution. Anyway, this feature will require a lot of time (a lot of benchmarks too...).

**Comment by Alkarex** [comment]
Thanks for the update @Shinokuni, great news 👍 
Let me know if I can help, for instance with some testing. Do you happen to have some development builds somewhere?
I can also provide sparring when it comes to the queries to perform for an efficient sync.
See e.g. https://github.com/FreshRSS/FreshRSS/issues/2566#issuecomment-541317776 (to get server changes; this part does not include pushing changes to the server, but I can provide that as well)

**Comment by Shinokuni** [comment]
Thanks, I will probably make a post on FreshRSS/FreshRSS#2566 to sum up the issues and what I would like to do.
