### ISSUE TITLE
Application crashes when entering an url without http scheme

### ISSUE THREAD

**Issue by prysme01** [readrops/Readrops#55]
Should be because of the SSO login of yunohost, but I would like to know how to connect freshrss hosted on yunohost to Readrops. Any hint ?

**Comment by prysme01** [comment]
I've found a workaround to disable SSO on a specific URL
sudo yunohost app setting "freshrss" skipped_uris -v "/api/greader.php"

anyway I remark that Readrops crash if you put the RSS url without the https://

**Comment by Shinokuni** [comment]
> anyway I remark that Readrops crash if you put the RSS url without the https://

I was able to reproduce. Did you have the same crash when using SSO ?

**Comment by prysme01** [comment]
I did not try again with the SSO as I have disabled it for this URL, in fact i don't know how to renable it :)

**Comment by Shinokuni** [comment]
> I did not try again with the SSO as I have disabled it for this URL, in fact i don't know how to renable it :)

I see :laughing: . Otherwise I will make a new release with the fix as it is quite annoying.

**Comment by Shinokuni** [comment]
Fixed in 467c6195907f32a4ea6409fe91e2d07790a2a55d.
