### ISSUE TITLE
[Feature Request] FreshRSS Read by category

### ISSUE THREAD

**Issue by prysme01** [readrops/Readrops#56]
Using FreshRSS : 
Could you please add an option to read articles by category. I have a bunch of categories sorted by subjects of interrest, I would be happy to read entries by selecting the category instead of having to select website under the category.

Thanks.

**Comment by Shinokuni** [comment]
It was already requested, but sadly, from an UX point of view, it is difficult to implement. When you click on a folder in the drawer, it opens its collapsed view.

I don´t know if I can handle the click depending if it was on the folder label or the collapse icon. This would be the best compromise.

**Comment by prysme01** [comment]
Thanks for taking this as an enhancement, Maybe a long click on the category can do the trick, or a new icon on the left, or maybe an option in the setting to not deploy the category but to read then directly.

Anyway your app is really good, i am waiting for this enhancement to fully use it every day.
Thanks for your work and your time !

**Comment by zoenglinghou** [comment]
Other RSS readers collapses/expands while you tap on the arrow, but shows the category article list when you tap on the category. I think this might be a good way to implement the feature

**Comment by attam** [comment]
I second this request...have tried various open source RSS feed readers, and still searching for the best. Just landed on readrops and really like it, but would not switch unless I had this feature. I use opml as the source for my feeds and organize by topic, so would like to read 'all' feeds in the "news "folder/all feeds in the "science" folder, etc. I'm going to keep the app on my phone for now. Great work!

**Comment by ljoonal** [comment]
This is the main reason why I'm still stuck running a very outdated and buggy client on my phone. I think that a long press would be quite reasonable. Although I feel like long pressing would be better for expanding, and a short press could open the category page. The dropdown arrow would be good to also be kept, so that someone who hasn't figured out the long press wouldn't still miss out on the functionality.

**Comment by GLLM** [comment]
Hello all,
I've just discovered Readrops ... which looks like a great project !!
Prior to this, I've been using the now-unmaintained/old/ EasyRSS.

This is the feature I most miss in Readrops !

I hope it will see the daylight, on day

GLLM

**Comment by Shinokuni** [comment]
Added in 725c20a78e380ae5cf6d988a25ada238c51cbd08.

**Comment by GLLM** [comment]
Thanks @Shinokuni for the work !
I cannot wait for the next release then :)
