### ISSUE TITLE
incorrect category name parsing

### ISSUE THREAD

**Issue by klausmcm** [readrops/Readrops#61]
I'm using this with my own instance of FreshRSS (v1.15.3).

I have one category in FreshRSS

![image](https://user-images.githubusercontent.com/14914359/78524126-e8e78a00-7787-11ea-8753-c97a6ea464a9.png)

The issue is that *Readrops* displays that category as

![image](https://user-images.githubusercontent.com/14914359/78524175-0caad000-7788-11ea-8e17-6420d6ff620a.png)

Everything before the slash gets dropped. Not sure if this is a bug or expected.

**Comment by Shinokuni** [comment]
Hello, 
yes this is a bug. Thanks for reporting it.

**Comment by Shinokuni** [comment]
Fixed in bf48caf69447bc9598166617a2fd8f9ac43bf145.

**Comment by klausmcm** [comment]
Thank you! I look forward to when fdroid is updated with the new release.
