### ISSUE TITLE
Can't subscribe a feed provided from feedburner

### ISSUE THREAD

**Issue by mszet** [readrops/Readrops#71]
Subscription example:
+
Feed Url 
https://feeds.feedburner.com/HaveIBeenPwnedLatestBreaches
Results
☑️ https://feeds.feedburner.com/HaveIBeenPwnedLatestBreaches
Validate
Network failure when accessing feed https://feeds.feedburner.com/HaveIBeenPwnedLatestBreaches
WTF?

Subscribtions not from feedburner are working and updated.

Greeting
mszet

**Comment by Shinokuni** [comment]
Thanks; I will check out.

**Comment by Shinokuni** [comment]
So Github closes issues automatically :thinking: .
