### ISSUE TITLE
Ordering articles according to publication date

### ISSUE THREAD

**Issue by ISs25u** [readrops/Readrops#74]
Hi !

Thank you for the app, I think it's one of the best looking and useful on Android !

I have just one regret concerning the ordering of the articles. When I choose "Newest to Oldest" it actually first groups the articles by source then order them by date. When having a lot of sources publishing a lot it is difficult to follow the news and requires to scroll a lot. I would like to be able to order **all** the articles by date without regarding its source.

Do you think this feature would not be to difficult to implement ?

**Comment by Shinokuni** [comment]
Hello, thanks for your interest in Readrops!

Newest to Oldest sort is based on items ids. So it's logical to have articles sorted by group if you add a new feed, its items will be added one by one and will appear the same way in the list.

I know it isn't the best way to sort items, I have seen multiple people complaining about that. I will change it to respect items publication date.

**Comment by Shinokuni** [comment]
Added in 2c7e5de2946e50ef9929566d815abaa59833a969.
