### ISSUE TITLE
Cannot remove "read it later" articles

### ISSUE THREAD

**Issue by fluxtendu** [readrops/Readrops#75]
Hi,

I cannot find an UI option to remove articles from "read it later" section

I use Readrops 1.2.0 on Android 10 with french language

Thanks

**Comment by Shinokuni** [comment]
Hi,

It is not possible currently. This section needs a bit of rework, surely for 1.3.

**Comment by Shinokuni** [comment]
Items from the read it later category can now be removed from it.
