### ISSUE TITLE
Light theme is not light when system is in dark mode

### ISSUE THREAD

**Issue by andreyorst** [readrops/Readrops#76]
In Android 10 it is possible to use system-wide dark mode, and apps are now can follow system settings. It's great that Readrops follows the setting (maybe unintentionally), but I would like to keep the light background, as not all feeds look good on dark background (maybe that's because the theme is set to light)

Here's a dark theme:
![Screenshot_2020-09-04-20-15-13-162_com readrops app](https://user-images.githubusercontent.com/19470159/92268651-74a64380-eeeb-11ea-835d-e79bda0237a9.jpg)

Here's a light theme:
![Screenshot_2020-09-04-20-15-18-204_com readrops app](https://user-images.githubusercontent.com/19470159/92268654-75d77080-eeeb-11ea-8519-534f3d4d2b14.jpg)
It's even darker than the *dark* theme.

My suggestion is to add "Follow system theme" switch to the list, that will keep current behavior and allow to force light theme by selecting "Light" switch.

Thanks for the great RSS reader

**Comment by Shinokuni** [comment]
That's weird because Readrops doesn't have any kind of support for the "Following system theme" feature, so that's indeed unintentionally. You definitely should be able to set your theme independently of the system.   

> as not all feeds look good on dark background (maybe that's because the theme is set to light)

Do you have some feeds colors which are too bright or too dark? Which version of Readrops are you using? 1.2 is supposed to drop colors which are too bright or too dark. You may want to reload feeds colors in the settings.

**Comment by andreyorst** [comment]
I'm using Version 1.2.0(11) installed from F-Droid on Android 10 MIUI12.0.1

> Do you have some feeds colors which are too bright or too dark?

No, The issue is that some feeds just use images with non-transparent light background, like LaTeX formulas, of graphs. There's not much you could or should do with that, it's just doesn't mix well with dark theme

**Comment by Shinokuni** [comment]
I see. 

Anyway, I will fix this theme issue and add an option to follow the system theme.

**Comment by andreyorst** [comment]
A bit more info. I;ve discovered that recent update brought mea. special swithc that allows me to choose in the system settings what apps are affected by dark mode. I can opt out Readrops from this list and therefore this bug disappears. However some apps seem to support the dark mode fearure natively and are toggled off in this list but still follow the system theme. It seems that MIUI hacks colors in apps to make them dark if app has no native support for the dark mode.
