### ISSUE TITLE
Failure to parse feed? (0 articles from a feed that definately has articles)

### ISSUE THREAD

**Issue by kitlith** [readrops/Readrops#77]
A [feed](https://github.com/readrops/Readrops/files/5253803/13918209.txt) that demonstrates the issue for me. It's currently served with `Content-Type: text/xml` iirc

This same feed works in a number of other readers, so I don't think it's my fault as the one generating it, and it's not due to a timeout so far as I can tell, so IDK what the issue is, other than maybe the kludgy `<!-- keepalive -->` causing issues.

**Comment by Shinokuni** [comment]
Your feed items don't have any date. Currently, Readrops can't insert items which don't have any date. The main reason is that I don't know how to deal with this kind of item as sort is based on the date.

If your feed works with others readers, then there should be a solution. Could you give me the url of your feed so I can test it with some readers?

**Comment by kitlith** [comment]
I think those other readers default to the current datetime.

I'd have given you a full URL to begin with if it wasn't a server running on localhost. Specifically, that feed was generated with https://github.com/kitlith/ao3rss_rs with a url of `http://127.0.0.1:8000/work/13918209`, but I figure it'll probably be easier for you to just host that feed file statically somewhere while you investigate.

Meanwhile, I can work on adding the datetime to the generated feed, so that it'll be compatible with more readers.

**Comment by kitlith** [comment]
Welp, found another bug of some sort, assuming i didn't make some sort of mistake. I put that feed up as a gist (https://gist.githubusercontent.com/kitlith/5dbb727a371c657cf94ffacf56d0e43c/raw/0b8af2e8c6175aea3320c1976638c16412b6864b/19731253.rss) which resulted in an `Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference` and no option to add the feed, which is an entirely different behavior. :/

**Comment by Shinokuni** [comment]
I tested your gist with some readers, and indeed they fallback to the current date time. As I'm working on a new local parser for 1.3, the support for missing dates will only be available in this release.

Otherwise, I fixed the gist url parsing bug. I will make a new release soon with the fix.
