### ISSUE TITLE
Help/Bug: cannot add certain RSS feeds to the app

### ISSUE THREAD

**Issue by MPeti1** [readrops/Readrops#83]
Hi! I'm a fairly new user, and I'm unable to add RSS feeds to the app.

I have tried these feeds with the following results:

URL | Example feed | Problem
:-:|:-|:-:
nitter.net | https://nitter.net/twitter/rss | a feed is found, validation never ends
signal.org | https://signal.org/blog/rss.xml | No feeds are found by the app
factorio.com | https://factorio.com/blog/rss | a feed is found, validation never ends
theverge.com | https://theverge.com/rss/index.html | a feed is found*, but validation never ends

*actually 2 if I only enter the domain. I included this one because it's on the screenshots, so a feed you know (how) it works could help in debugging

I have the F-droid app (version 1.2.0 (11)), and I'm trying to use a local account
also, I'm new to RSS readers altogether, so please forgive me if I've broken something. what I know is that an app called I've used Feeder previously, and it works with the first 3 feed

**Comment by Shinokuni** [comment]
Hello, Readrops got a new local parser which will be available in 1.3. All your feeds work with it (although you have to replace ".html" by ".xml" for theverge feed).

You will have to wait for 1.3 release to have all your feeds work as I won't try to fix the old parser.

**Comment by MPeti1** [comment]
Ok, thank you! Are there plans about when that could be expected?

**Comment by Shinokuni** [comment]
I would like to release 1.3 at the end of December/beginning of January. I hope I will have enough to respect this schedule.

**Comment by MPeti1** [comment]
Thank you! Is there a known workaround for the meantime? Even if it includes modification of the app's data files on /data/data, or building and installing the master branch

**Comment by Shinokuni** [comment]
You can make yourself a debug build, but it is currently unstable. Even if the new parser is ready and backed by a very good test coverage, some others parts could make the app crash. I advise you to only use the local account.

**Comment by Shinokuni** [comment]
v1.3.0 is out, so let me know if you have still problems with some RSS feeds.

**Comment by MPeti1** [comment]
For now it's pretty ok, thank you!

The only issue I've found is that when I put a feed in a folder, it won't immediately show that it's in a folder now, but only after reopening the 'Feeds and folders' menu from the account settings

**Comment by Shinokuni** [comment]
It's a known bug, not really blocking, it will be fixed for 1.4 I think.
