### ISSUE TITLE
Replacement for deprecated user API endpoint

### ISSUE THREAD

**Issue by anoymouserver** [readrops/Readrops#86]
According to nextcloud/news#935 the deprecated `/api/v1-2/user` endpoint will be removed in version 16.0, the app could use the Nextcloud APIs instead for the user data. More info about the user api here: [Legacy API](https://github.com/nextcloud/news/blob/master/docs/externalapi/Legacy.md#user)

**Comment by Shinokuni** [comment]
Thanks for warning me. I will migrate to the Nextcloud API.

**Comment by Shinokuni** [comment]
Added in f2607c307c067062c1383510e0e10a4462de3517.
