### ISSUE TITLE
Breaking change in News 15.1.0

### ISSUE THREAD

**Issue by Grotax** [readrops/Readrops#87]
#### Brief description of the issue.

With news 15.1.0 we have a change in the feed attribute "folderId", if the feed is in the root folder the id will be "null" instead of 0.

See https://github.com/nextcloud/news/issues/939

#### How to reproduce the bug?

1. Install 15.1.0-rc2
2. sync
3. ...

#### What was the expected result?

Accept both 0 and null as a value at least for a while to allow for a smooth transition.

**Comment by Shinokuni** [comment]
Thanks for telling me. What about `/feeds/{feedId}/move` which has a `folderId` attribute when you want to move a feed to the root?

**Comment by Grotax** [comment]
It should also be null, might not work at the moment we are still testing.

**Comment by anoymouserver** [comment]
I've tested all occurences where the root folder is a valid input. They currently work with both `null` and `0`
https://github.com/nextcloud/news/issues/939#issuecomment-725904099

**Comment by Shinokuni** [comment]
It is stated in the documentation for call `/feeds/{feedId}/move` to use a null value like this: `"folderId" : null`, yet it gives me an 500 error. It only works like this: `"folderId : "null"`. Is this a wanted behavior?

**Comment by Grotax** [comment]
@Shinokuni which version of news are you using?

I just tested it with 15.1.0-rc3 in insomnia and null worked fine

**Comment by Shinokuni** [comment]
Sorry, I should have added it. I'm using 14.2.2. So I should wait for at least 15.1.0 before using null for this call.

**Comment by Grotax** [comment]
Yea we are basically waiting for clients to update or at least give the maintainers a chance before we push 15.1.0 as an update to all users.

But there will always be someone with a incomparable version combination.

**Comment by Shinokuni** [comment]
I have just created a new release with the fix. I will keep an eye on news version for `/feeds/{feedId}/move` call.
