### ISSUE TITLE
Support Oauth2 authentication mechanisms

### ISSUE THREAD

**Issue by pstn** [readrops/Readrops#88]
This feature might be out of scope for this project because neither freshrss nor nextcloud support oauth2 natively.
However, they both support auth via proxy so it's possible to set software like [oauth2 proxy](https://github.com/oauth2-proxy/oauth2-proxy) and thereby minimizing the attack surface of the application while providing a more secure auth mechanism (at least for freshrss that doesn't natively support 2FA).
Unfortunately my java skills are basically nonexistant, so I can't PR this, but I'd  be willing to provide a oauth2_proxy secured nextcloud or freshrss instance for testing purposes.

**Comment by Shinokuni** [comment]
As I'm planning to support other services which support OAuth2, it isn't out of scope.

> but I'd be willing to provide a oauth2_proxy secured nextcloud or freshrss instance for testing purposes.

It will be very appreciated!

**Comment by pstn** [comment]
It seems like using the app passwords provided by freshrss is the superior alternativ. Nextcloud has similar mechanisms, so I'm closing this.
