### ISSUE TITLE
Cannot create nextcloud account: certPathValidatorException

### ISSUE THREAD

**Issue by yaute74** [readrops/Readrops#90]
Hello,

I have to create an account for my Nextcloud install on my Raspberry Pi.
But I have this error:
`java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.`

The android nextcloud application and Davx5 work fine.

Regards,
Yaute

**Comment by Shinokuni** [comment]
Hello,

Are you using a self-signed certificate? Readrops doesn't currently support those certificates.

**Comment by yaute74** [comment]
Ok thank for the info
