### ISSUE TITLE
What does right-swipe do? (+ Enhancement request)

### ISSUE THREAD

**Issue by keunes** [readrops/Readrops#94]
Hello

As noted elsewhere I'm coming from Flym and looking for a new ESS reader app. I'm interested in Readrop - thanks for this contribution to the open source community!

As I'm discovering the app, I'm wondering about a few things. One of them is: what does right-swipe do? Swiping right reveals a 'download' icon, but proceeding with the swipe removes the entry from the list.

Does right-swipe indeed remove an item?
If yes, it would be a helpful enhancement if the background colour is read instead of blue, and the icon some sort of cross or wastebin instead of a download/save icon.
If not, then what does it do? :)

Thanks again!

**Comment by Shinokuni** [comment]
Hello, right to swipe put the item into the read later category. It's a local category where you can save articles you would like to read but not immediately, like long articles.

 I admit that the icon isn't really self-explanatory, and I plan to change it for 1.3.

**Comment by keunes** [comment]
Sorry for replying only now - thanks for the explanation :)  Another icon would indeed be helpful.

**Comment by Shinokuni** [comment]
The icon was changed in 056d8db78f6e22b7f359bb9f9db2132a52d79c3f.
