### ISSUE TITLE
When I try to login I get 400 error (FreshRSS)

### ISSUE THREAD

**Issue by 360fun** [readrops/Readrops#98]
Hi, I self-host FreshRSS (1.16.2) and use it through several clients (EasyRSS/FreshRSS on Android and Reeder on Mac) without any problems.

Installed extensions (no idea if might help):
![image](https://user-images.githubusercontent.com/844090/104126375-7762ea80-535c-11eb-8d12-ebd9ddb74ad3.png)

Sadly this is what happens when I try to login with Readrops:
![image](https://user-images.githubusercontent.com/844090/104126168-5b127e00-535b-11eb-8dfc-aacb3ce37030.png)

I use the greader API (".../p/api/greader.php/") with the other RSS clients and it works perfectly. 😕

**Comment by Shinokuni** [comment]
Did you set an API password? It is different from your login password (go to Configuration > Profile as written on the login screen).

**Comment by 360fun** [comment]
Of course, I use the login with the other apps and they work, so must be something about Readrops.

**Comment by 360fun** [comment]
Any help?

Btw I found weird that Readrops is not listed in the compatible clients:
https://freshrss.github.io/FreshRSS/en/users/06_Mobile_access.html

Maybe my problem has something to do with:
> Or use a client that does not escape slashes (such as EasyRSS), in which case proceed to step 6.

**Comment by Alkarex** [comment]
See my response https://github.com/FreshRSS/FreshRSS/issues/3396#issuecomment-766428582
If might simply be due to the fact that it is sufficient in Readrops to type the root address of your FreshRSS instance, and not its full explicit API address

**Comment by Alkarex** [comment]
P.S. Our doc is not so up to date, a newer list of clients including Readrops can be seem on our main page:
https://github.com/FreshRSS/FreshRSS#apis--native-apps

**Comment by 360fun** [comment]
> See my response [FreshRSS/FreshRSS#3396 (comment)](https://github.com/FreshRSS/FreshRSS/issues/3396#issuecomment-766428582)
> If might simply be due to the fact that it is sufficient in Readrops to type the root address of your FreshRSS instance, and not its full explicit API address

Yes! This solved the problem!!! THANKS!!! 😄
I really hope Readrops will make this more clear in the UI and/or creating some FAQ 🙏
